# .github/workflows/release.yml
name: Make Release on Tag Push

on:
  push:
    tags:
      - '*.*.*'  # Simple semantic version v1.2.3

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Go configuration
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          distribution: goreleaser
          workdir: .
          install-only: false
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
