# .github/workflows/release.yml
name: Crear Release con GoReleaser

on:
  push:
    tags:
      - 'v*.*.*'  # Simple semantic version v1.2.3

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Go configuration
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser release --rm-dist
